
## **BPNN**


- M Aidan Daffa J


[Link Google Colab](https://colab.research.google.com/drive/10_nP7kuSMH3YdlviZ-S9EUaZhrRXRVvO?usp=sharing)




In [ ]:
#Import Library
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Load Iris dataset
column_names=["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm", 'Species']
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",names=column_names)

X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species'].values.reshape(-1, 1)
df.isnull().sum()


SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
# One-Hot Encoding
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y.reshape(-1, 1))

# Split dataset into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Define the activation function (sigmoid)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define the derivative of the activation function
def sigmoid_derivative(x):
    return x * (1 - x)

# Set the number of input, hidden, and output layers
input_layer_neurons = X.shape[1]
hidden_layer_neurons = 12
output_layer_neurons = y.shape[1]

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
print(X_train)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
8              4.4           2.9            1.4           0.2
88             5.6           3.0            4.1           1.3
136            6.3           3.4            5.6           2.4
142            5.8           2.7            5.1           1.9
91             6.1           3.0            4.6           1.4
..             ...           ...            ...           ...
103            6.3           2.9            5.6           1.8
100            6.3           3.3            6.0           2.5
123            6.3           2.7            4.9           1.8
128            6.4           2.8            5.6           2.1
1              4.9           3.0            1.4           0.2

[105 rows x 4 columns]


In [ ]:


# Initialize the weights and biases with random values
hidden_weights = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))-0.5
hidden_bias = np.random.uniform(size=(1, hidden_layer_neurons))-0.5
output_weights = np.random.uniform(size=(hidden_layer_neurons, output_layer_neurons))-0.5
output_bias = np.random.uniform(size=(1, output_layer_neurons))-0.5


print(hidden_weights)
print("\n\n")
print(hidden_bias)
print("\n\n")
print(output_weights)
print("\n\n")
print(output_bias)

[[-0.12779104 -0.11151775 -0.27700541  0.42423934  0.08385537  0.18408538
  -0.34258757 -0.42493713 -0.12678736  0.17581123 -0.28169948 -0.15943527]
 [ 0.3980385  -0.18817749  0.27489785  0.45069284  0.36273406  0.15009894
  -0.38649972  0.30562501  0.30328898  0.23936689  0.42227374 -0.28387378]
 [ 0.09725929 -0.34401853 -0.44092878  0.26655097 -0.32824631  0.27945952
  -0.2218258  -0.17239743  0.32400548 -0.41832544  0.45313609  0.39588753]
 [ 0.26527541  0.25527874 -0.03331169  0.19661323  0.29805458 -0.24301939
  -0.08890587 -0.24052431  0.11356179 -0.0314518  -0.17534547 -0.12346896]]



[[-0.17225337  0.31689284  0.24940623 -0.19172695  0.30290742  0.43045414
  -0.31018183  0.18617776 -0.3458452   0.45590961 -0.38013547 -0.33916756]]



[[ 0.02940416  0.34704888 -0.26387358]
 [-0.22989751 -0.39097106 -0.25693459]
 [-0.30913829  0.04499728 -0.1506545 ]
 [-0.18768207  0.01720962 -0.34968325]
 [ 0.05909645 -0.11676051  0.19840606]
 [ 0.26806591  0.266348    0.21056042]
 [-0.01721802

In [ ]:
# Set the number of epochs and learning rate
epochs = 10000
learning_rate = 0.1
loss_threshold = 0.05


In [ ]:
# Train the neural network
for i in range(epochs):
    # Forward propagation
    hidden_layer_input = np.dot(X_train, hidden_weights)
    hidden_layer_input += hidden_bias
    hidden_layer_activation = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_activation, output_weights)
    output_layer_input += output_bias
    predicted_output = sigmoid(output_layer_input)

    # Compute loss
    loss = np.mean(np.square(y_train - predicted_output))

    # Check if loss has reached threshold
    if loss < loss_threshold:
        print("Training stopped at epoch:", i+1)
        break

    # Backpropagation
    error = y_train - predicted_output
    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(output_weights.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_activation)

    # Updating Weights and Biases
    output_weights += hidden_layer_activation.T.dot(d_predicted_output) * learning_rate
    output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    hidden_weights += X_train.T.dot(d_hidden_layer) * learning_rate
    hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate



Training stopped at epoch: 4430


In [ ]:
print(output_weights)
print(output_bias)
print(hidden_weights)
print(hidden_bias)

[[ 2.06649755  2.05124911 -2.58449561]
 [-0.0251607  -0.17417694 -0.58153312]
 [ 0.13900566  0.94757637 -1.1329959 ]
 [-1.86754243 -0.95793923  1.61790127]
 [ 8.48489815 -7.05024921 -3.836506  ]
 [ 0.54364329  1.11287223 -1.60050102]
 [-1.4182161   0.03295635  0.46295716]
 [ 0.75083275 -0.0763766  -0.60888271]
 [-0.20594576  1.04121935 -1.37773399]
 [ 0.49632573 -0.7508777  -0.73728552]
 [-2.44255825 -1.06618533  2.13523638]
 [ 0.15339242  1.20047764 -0.79975969]]
[[-2.95447672 -0.91038514  0.07438883]]
                     0         1         2         3         4         5   \
SepalLengthCm  4.864306 -0.500602 -0.270607 -3.281334  0.396765 -0.179656   
SepalWidthCm   4.191180 -0.153924  0.489033 -2.298653  2.835020  0.242568   
PetalLengthCm -7.617434 -1.171145 -3.238449  1.858407 -4.895584 -3.087185   
PetalWidthCm  -5.229683 -0.087734 -1.820640  1.735469 -1.806709 -2.300460   

                     6         7         8         9         10        11  
SepalLengthCm  2.420205 -1.33

In [ ]:
# Test the neural network
hidden_layer_input = np.dot(X_test, hidden_weights)
hidden_layer_input += hidden_bias
hidden_layer_activation = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_activation, output_weights)
output_layer_input += output_bias
predicted_output = sigmoid(output_layer_input)



In [ ]:
# Compute the accuracy
predicted_class = np.argmax(predicted_output, axis=1)
true_class = np.argmax(y_test, axis=1)
accuracy = np.mean(predicted_class == true_class)
print("Accuracy:", accuracy)

Accuracy: 0.9333333333333333
